from unittest.mock import MagicMock
from uuid import uuid4
from datetime import datetime, UTC
import pytest
from fastapi import HTTPException

from app.services.conversation_service import ConversationService
from app.db.models.conversation import Conversation, ConversationStatus
from app.db.models.artifact import Artifact
from app.db.models.message import Message
from app.db.models.execution_history import ExecutionHistory


@pytest.fixture
def mock_uow():
    uow = MagicMock()

    uow.conversations = MagicMock()
    uow.messages = MagicMock()
    uow.artifacts = MagicMock()
    uow.execution = MagicMock()

    return uow





def create_conversation():
    conversation = Conversation(
        request_id=uuid4(),
        user_query="Generate Login API",
        status=ConversationStatus.COMPLETED,
    )

    # Simulate values normally generated by the DB
    conversation.id = uuid4()
    conversation.created_at = datetime.now(UTC)
    conversation.updated_at = datetime.now(UTC)

    return conversation


def create_message(conversation_id):
    return Message(
        conversation_id=conversation_id,
        role="user",
        content="Hello",
        agent_name="User",
    )


def create_artifact(conversation_id):
    return Artifact(
        conversation_id=conversation_id,
        filename="main.py",
        artifact_type="python",
        description="code",
        content="print('Hello')",
    )


def create_execution(conversation_id):
    start = datetime.now(UTC)

    return ExecutionHistory(
        conversation_id=conversation_id,
        agent_name="Planner",
        status="success",
        latency_ms=120,
        started_at=start,
        ended_at=start,
    )


def test_list_conversations(mock_uow):
    conversation = create_conversation()

    mock_uow.conversations.list.return_value = [conversation]
    mock_uow.conversations.count.return_value = 1

    service = ConversationService(mock_uow)

    result = service.list_conversations()

    assert len(result.conversations) == 1
    assert result.pagination.total_items == 1
    assert result.pagination.total_pages == 1

    mock_uow.conversations.list.assert_called_once()
    mock_uow.conversations.count.assert_called_once()



def test_list_conversations_empty(mock_uow):
    mock_uow.conversations.list.return_value = []
    mock_uow.conversations.count.return_value = 0

    service = ConversationService(mock_uow)

    result = service.list_conversations()

    assert result.conversations == []
    assert result.pagination.total_items == 0
    assert result.pagination.total_pages == 0


def test_get_conversation(mock_uow):
    conversation = create_conversation()

    mock_uow.conversations.get.return_value = conversation
    mock_uow.messages.list_by_conversation.return_value = [
        create_message(conversation.id)
    ]
    mock_uow.artifacts.list_by_conversation.return_value = [
        create_artifact(conversation.id)
    ]
    mock_uow.execution.list_by_conversation.return_value = [
        create_execution(conversation.id)
    ]

    service = ConversationService(mock_uow)

    result = service.get_conversation(conversation.id)

    assert result.conversation.id == conversation.id
    assert len(result.messages) == 1
    assert len(result.artifacts) == 1
    assert len(result.execution_history) == 1


def test_get_conversation_not_found(mock_uow):
    mock_uow.conversations.get.return_value = None

    service = ConversationService(mock_uow)

    with pytest.raises(HTTPException) as exc:
        service.get_conversation(uuid4())

    assert exc.value.status_code == 404
    assert exc.value.detail == "Conversation not found"


def test_delete_conversation(mock_uow):
    conversation = create_conversation()

    mock_uow.conversations.get.return_value = conversation

    service = ConversationService(mock_uow)

    service.delete_conversation(conversation.id)

    mock_uow.conversations.delete.assert_called_once_with(conversation)
    mock_uow.commit.assert_called_once()


def test_delete_conversation_not_found(mock_uow):
    mock_uow.conversations.get.return_value = None

    service = ConversationService(mock_uow)

    with pytest.raises(HTTPException):
        service.delete_conversation(uuid4())

    mock_uow.commit.assert_not_called()