"""remove task from artifacts

Revision ID: 25174937aca3
Revises: 3730ff01f9bb
Create Date: 2026-07-17 22:22:59.087211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25174937aca3'
down_revision: Union[str, Sequence[str], None] = '3730ff01f9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
